Modificacoes para rodar o script
analytics-ufcg/versoes-de-proposicoes pull request #4
Opened 2019-05-10 19:10 UTC by jairNeto

Modificações no código para rodar o script que automatiza a análise de todas as emendas existentes no Leg.go

2019-05-23 18:22 UTC, JuanBarros2 requested changes

2019-05-23 18:22 UTC, JuanBarros2 commented on calcula_distancias_emendas.sh
> +python3 download_csv_prop.py ../../../versoes-de-proposicoes/versoes_leggo.csv ../../../versoes-de-proposicoes/emendas/
não existe a pasta de emendas

2019-06-06 12:31 UTC, tarcisocomp commented on R/process_data.R
> +    dplyr::mutate(codigo_emenda = as.character(codigo_emenda))
Seria bom trocar o nome da variável codigo_emenda para id_emenda, pra ficar mais explicativo (o termo id já é reservado pra esse tipo de coisa, em especial no contexto das APIs de Dados Abertos).

2019-06-06 12:34 UTC, tarcisocomp commented on R/process_data.R
> +    dplyr::anti_join(emendas_df, emendas_raw, by=c("codigo_texto" = "codigo_emenda")) %>%
Essa variável emendas_df não existe na função. Seria df?

2019-06-06 12:38 UTC, tarcisocomp commented on fetcher.R
> +df <- fetch_data(args$input)
Colocar nomes mais descritivos nessas variáveis. Df deveria ser algo do tipo: textos_proposicao

2019-06-06 12:40 UTC, tarcisocomp commented on fetcher.R
> +df <- fetch_data(args$input)
A mesma coisa pra as funções fetch_data e save_new_data. Deveria ser algo do tipo: fetch_textos_proposicao() e save_new_emendas()

2019-06-06 12:43 UTC, tarcisocomp commented on calcula_distancias_emendas.sh
> +Rscript fetcher.R -i ../leggoR/data/tabela_geral_ids_casa.csv -e ../leggo-backend/data/emendas_raw.csv -o versoes_leggo.csv -a avulso.csv
O arquivo de output não deveria ser versoes_leggo.csv. Isso não representa o dado que ele guarda. O nome deveria ser algo do tipo: novas_emendas.csv

2019-06-06 12:45 UTC, tarcisocomp commented on calcula_distancias_emendas.sh
> +Rscript fetcher.R -i ../leggoR/data/tabela_geral_ids_casa.csv -e ../leggo-backend/data/emendas_raw.csv -o versoes_leggo.csv -a avulso.csv
Esse arquivo avulso.csv também poderia ter um nome mais explicativo: avulsos_iniciais.csv / textos_iniciais_props.csv

2019-06-07 19:31 UTC, merged